// <auto-generated />
using System;
using FantasyBasket.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FantasyBasket.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260117175105_SetDefaultRosterLimits")]
    partial class SetDefaultRosterLimits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FantasyBasket.API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FantasyTeamName")
                        .HasColumnType("text");

                    b.Property<string>("GeneralManagerName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<double>("TotalCareerFantasyPoints")
                        .HasColumnType("double precision");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CurrentOfferTotal")
                        .HasColumnType("double precision");

                    b.Property<int>("CurrentOfferYears")
                        .HasColumnType("integer");

                    b.Property<double>("CurrentYear1Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HighBidderId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("LeagueId", "IsActive");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<string>("BidderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double precision");

                    b.Property<int>("Years")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractYears")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<double>("SalaryYear1")
                        .HasColumnType("double precision");

                    b.Property<double>("SalaryYear2")
                        .HasColumnType("double precision");

                    b.Property<double>("SalaryYear3")
                        .HasColumnType("double precision");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.DailyLineup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BenchOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("boolean");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId", "Date");

                    b.ToTable("DailyLineups");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentSeason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvitationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("LogoData")
                        .HasColumnType("bytea");

                    b.Property<double>("MinBidAmount")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SalaryCap")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("SeasonStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvitationCode")
                        .IsUnique();

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.LeagueSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AssistWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("BlockWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("CurrentSeason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<double>("MinBidAmount")
                        .HasColumnType("double precision");

                    b.Property<int>("PlayoffTeams")
                        .HasColumnType("integer");

                    b.Property<double>("PointWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("ReboundWeight")
                        .HasColumnType("double precision");

                    b.Property<int>("RoleLimitCenters")
                        .HasColumnType("integer");

                    b.Property<int>("RoleLimitForwards")
                        .HasColumnType("integer");

                    b.Property<int>("RoleLimitGuards")
                        .HasColumnType("integer");

                    b.Property<int>("RosterSlotsBench")
                        .HasColumnType("integer");

                    b.Property<int>("RosterSlotsC")
                        .HasColumnType("integer");

                    b.Property<int>("RosterSlotsF")
                        .HasColumnType("integer");

                    b.Property<int>("RosterSlotsG")
                        .HasColumnType("integer");

                    b.Property<int>("RosterSlotsIR")
                        .HasColumnType("integer");

                    b.Property<int>("RosterSlotsPF")
                        .HasColumnType("integer");

                    b.Property<int>("RosterSlotsPG")
                        .HasColumnType("integer");

                    b.Property<int>("RosterSlotsSF")
                        .HasColumnType("integer");

                    b.Property<int>("RosterSlotsSG")
                        .HasColumnType("integer");

                    b.Property<int>("RosterSlotsUtil")
                        .HasColumnType("integer");

                    b.Property<double>("SalaryCap")
                        .HasColumnType("double precision");

                    b.Property<double>("SalaryFloor")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("SeasonEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SeasonStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("StealWeight")
                        .HasColumnType("double precision");

                    b.Property<double>("TurnoverWeight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId")
                        .IsUnique();

                    b.ToTable("LeagueSettings");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Matchup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AwayScore")
                        .HasColumnType("double precision");

                    b.Property<string>("AwayTeamId")
                        .HasColumnType("text");

                    b.Property<string>("AwayTeamPlaceholder")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("HomeScore")
                        .HasColumnType("double precision");

                    b.Property<string>("HomeTeamId")
                        .HasColumnType("text");

                    b.Property<string>("HomeTeamPlaceholder")
                        .HasColumnType("text");

                    b.Property<bool>("IsPlayed")
                        .HasColumnType("boolean");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueId", "IsPlayed", "WeekNumber");

                    b.ToTable("Matchups");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgAssists")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgBlocks")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgMinutes")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgPoints")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgRebounds")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgSteals")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgTurnovers")
                        .HasColumnType("double precision");

                    b.Property<double>("DefRebounds")
                        .HasColumnType("double precision");

                    b.Property<double>("DoubleDoubles")
                        .HasColumnType("double precision");

                    b.Property<double>("Efficiency")
                        .HasColumnType("double precision");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<double>("FantasyPoints")
                        .HasColumnType("double precision");

                    b.Property<double>("FgPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("Fga")
                        .HasColumnType("double precision");

                    b.Property<double>("Fgm")
                        .HasColumnType("double precision");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FtPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("Fta")
                        .HasColumnType("double precision");

                    b.Property<double>("Ftm")
                        .HasColumnType("double precision");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InjuryBodyPart")
                        .HasColumnType("text");

                    b.Property<string>("InjuryReturnDate")
                        .HasColumnType("text");

                    b.Property<string>("InjuryStatus")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NbaTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OffRebounds")
                        .HasColumnType("double precision");

                    b.Property<double>("PersonalFouls")
                        .HasColumnType("double precision");

                    b.Property<double>("PlusMinus")
                        .HasColumnType("double precision");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ThreePa")
                        .HasColumnType("double precision");

                    b.Property<double>("ThreePm")
                        .HasColumnType("double precision");

                    b.Property<double>("ThreePtPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("TripleDoubles")
                        .HasColumnType("double precision");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("WinPct")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AvgPoints");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.PlayerSeasonStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgAssists")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgBlocks")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgMinutes")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgPoints")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgRebounds")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgSteals")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgTurnovers")
                        .HasColumnType("double precision");

                    b.Property<double>("DefRebounds")
                        .HasColumnType("double precision");

                    b.Property<double>("DoubleDoubles")
                        .HasColumnType("double precision");

                    b.Property<double>("Efficiency")
                        .HasColumnType("double precision");

                    b.Property<double>("FantasyPoints")
                        .HasColumnType("double precision");

                    b.Property<double>("FgPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("Fga")
                        .HasColumnType("double precision");

                    b.Property<double>("Fgm")
                        .HasColumnType("double precision");

                    b.Property<double>("FtPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("Fta")
                        .HasColumnType("double precision");

                    b.Property<double>("Ftm")
                        .HasColumnType("double precision");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<string>("NbaTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OffRebounds")
                        .HasColumnType("double precision");

                    b.Property<double>("PersonalFouls")
                        .HasColumnType("double precision");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<double>("PlusMinus")
                        .HasColumnType("double precision");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ThreePa")
                        .HasColumnType("double precision");

                    b.Property<double>("ThreePm")
                        .HasColumnType("double precision");

                    b.Property<double>("ThreePtPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("TripleDoubles")
                        .HasColumnType("double precision");

                    b.Property<double>("WinPct")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Season");

                    b.ToTable("PlayerSeasonStats");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Division")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("LogoContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("LogoData")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("UserId", "LeagueId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.TeamDeadCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DeadCaps");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("ProposerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "Status");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.TradeAcceptance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TradeId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeAcceptances");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.TradeOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FromUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("ToUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TradeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ToUserId");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeOffers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NbaGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GameTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NbaGameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NbaGames");
                });

            modelBuilder.Entity("PlayerGameLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("Blocks")
                        .HasColumnType("integer");

                    b.Property<double>("FantasyPoints")
                        .HasColumnType("double precision");

                    b.Property<string>("GameDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Minutes")
                        .HasColumnType("double precision");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Rebounds")
                        .HasColumnType("integer");

                    b.Property<int>("Steals")
                        .HasColumnType("integer");

                    b.Property<int>("Turnovers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameDate", "PlayerId");

                    b.ToTable("PlayerGameLogs");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Auction", b =>
                {
                    b.HasOne("FantasyBasket.API.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Bid", b =>
                {
                    b.HasOne("FantasyBasket.API.Models.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Contract", b =>
                {
                    b.HasOne("FantasyBasket.API.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasket.API.Models.Team", "Team")
                        .WithMany("Roster")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.DailyLineup", b =>
                {
                    b.HasOne("FantasyBasket.API.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasket.API.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.LeagueSettings", b =>
                {
                    b.HasOne("FantasyBasket.API.Models.League", "League")
                        .WithOne("Settings")
                        .HasForeignKey("FantasyBasket.API.Models.LeagueSettings", "LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Matchup", b =>
                {
                    b.HasOne("FantasyBasket.API.Models.ApplicationUser", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FantasyBasket.API.Models.ApplicationUser", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.PlayerSeasonStat", b =>
                {
                    b.HasOne("FantasyBasket.API.Models.Player", "Player")
                        .WithMany("SeasonStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Team", b =>
                {
                    b.HasOne("FantasyBasket.API.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasket.API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.TradeAcceptance", b =>
                {
                    b.HasOne("FantasyBasket.API.Models.Trade", null)
                        .WithMany("Acceptances")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasket.API.Models.TradeOffer", b =>
                {
                    b.HasOne("FantasyBasket.API.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasket.API.Models.Trade", null)
                        .WithMany("Offers")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FantasyBasket.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FantasyBasket.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyBasket.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FantasyBasket.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Auction", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.League", b =>
                {
                    b.Navigation("Settings");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Player", b =>
                {
                    b.Navigation("SeasonStats");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Team", b =>
                {
                    b.Navigation("Roster");
                });

            modelBuilder.Entity("FantasyBasket.API.Models.Trade", b =>
                {
                    b.Navigation("Acceptances");

                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
